### PR TITLE
Encode enum cases without associated values

### LINKED ISSUE #157: [Bug] enum cases are not encoded unless type specified
- [x] I have read the [documentation](https://swiftpackageindex.com/SwiftyLab/MetaCodable/main/documentation/metacodable).
- [x] I have read the [limitations](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable/limitations).
- [x] I could not find my [issue](https://github.com/SwiftyLab/MetaCodable/issues).

**Describe the bug**

Encoding of enums is missing

```swift
@Codable
enum Foo {
    case test
}
// generates:
extension Foo: Decodable {
    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: DecodingKeys.self)
        guard container.allKeys.count == 1 else {
            let context = DecodingError.Context(
                codingPath: container.codingPath,
                debugDescription: "Invalid number of keys found, expected one."
            )
            throw DecodingError.typeMismatch(Self.self, context)
        }
        let contentDecoder = try container.superDecoder(forKey: container.allKeys.first.unsafelyUnwrapped)
        switch container.allKeys.first.unsafelyUnwrapped {
        case DecodingKeys.test:
            self = .test
        }
    }
}

extension Foo: Encodable {
    func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .test:
            break
        }
    }
}

extension Foo {
    enum CodingKeys: String, CodingKey {
        case test = "test"
    }
    enum DecodingKeys: String, CodingKey {
        case test = "test"
    }
}
```

which means Foo.test just encodes to "{}" which is not useful and asymmetric to how it decodes

### PR DESCRIPTION
**Pull request by Amzd**
Fixes #157

This breaks some `@IgnoreCodingInitialized` tests but that API is too confusing for me. I have no idea what it is actually supposed to do, so I can't tell if the failing tests are actually breaking the intended use. A maintainer needs to look at that.

### CODE REVIEW

File: Sources/PluginCore/Variables/Enum/Switcher/TaggedEnumSwitcherVariable.swift [hunk 1]
```diff
@@ -150,6 +150,7 @@ extension EnumSwitcherVariable {
                             generatedCode
                         }
                     } else {
+                        preSyntax("\(values.first!)")
                         "break"
```
Comment (soumyamahunt) [inline Sources/PluginCore/Variables/Enum/Switcher/TaggedEnumSwitcherVariable.swift:153]: Suggestion: You can add logic to conditionally include this `break` syntax depending on whether `preSyntax` returns any syntax.

File: Tests/MetaCodableTests/CodedAt/CodedAtEnumTests.swift [hunk 2]
```diff
@@ -802,4 +802,103 @@ struct CodedAtEnumTests {
             #expect(json["int"] as? Int == 42)
         }
     }
+
+    struct WithoutAssociatedVariables {
```
Comment (soumyamahunt) [inline Tests/MetaCodableTests/CodedAt/CodedAtEnumTests.swift:806]: Suggestion: You can add test case for your original example as well, without the `CodedAt`. You can add it to `CodableTests`

File: Sources/PluginCore/Variables/Enum/Switcher/TaggedEnumSwitcherVariable.swift [hunk 3]
```diff
@@ -150,6 +150,7 @@ extension EnumSwitcherVariable {
                             generatedCode
                         }
                     } else {
+                        preSyntax("\(values.first!)")
```
Comment (soumyamahunt) [inline Sources/PluginCore/Variables/Enum/Switcher/TaggedEnumSwitcherVariable.swift]: I think this will cause unused variable warnings in case of your original example. Can you address that in someway? May be passing some flag to this `preSyntax` closure and customizing the output based on this flag?

**Comment by soumyamahunt** [comment]
> This breaks some @IgnoreCodingInitialized tests but that API is too confusing for me. I have no idea what it is actually supposed to do, so I can't tell if the failing tests are actually breaking the intended use. A maintainer needs to look at that.

Can you provide what is the error you getting? The change seems to be in the right direction. So the tests might need to be updated with latest data.

**Review by soumyamahunt — CHANGES_REQUESTED** [review]

**Comment by Amzd** [comment]
> Can you provide what is the error you getting?

```swift
@Codable
@IgnoreCodingInitialized
enum SomeEnum {
    case bool(_ variableBool: Bool = true)
}
```

this previously encoded to nothing which means now all the tests fail with diff:

```swift
 extension SomeEnum: Encodable {
     func encode(to encoder: any Encoder) throws {
         var container = encoder.container(keyedBy: CodingKeys.self)
         switch self {
         case .bool(_: _):
+            let _ = container.superEncoder(forKey: CodingKeys.bool)
-            break
```

and it is unclear to me whether this is expected behavior from `@IgnoreCodingInitialized` or if the tests were just wrong.

File: Sources/PluginCore/Variables/Enum/Switcher/TaggedEnumSwitcherVariable.swift (hunk 3 above)
Comment (Amzd) [reply Sources/PluginCore/Variables/Enum/Switcher/TaggedEnumSwitcherVariable.swift]: I changed nothing in the decoding part and there there is also an unused variable so this seems like skewed standards but I have fixed this.

**Comment by Amzd** [comment]
I believe the previous behavior of `@IgnoreCodingInitialized` was a bug as I think on enums it is only meant to ignore the associated values, not the whole value. This PR fixes the bug but this might break implementations relying on that bug as they may have misinterpreted `@IgnoreCodingInitialized` to mean "ignore encoding completely". Thoughts are appreciated, if you say the fix is fine then I update the old tests.

**Comment by soumyamahunt** [comment]
> > Can you provide what is the error you getting?
> 
> ```swift
> @Codable
> @IgnoreCodingInitialized
> enum SomeEnum {
>     case bool(_ variableBool: Bool = true)
> }
> ```
> this previously encoded to nothing which means now all the tests fail with diff:
> 
> ```swift
>  extension SomeEnum: Encodable {
>      func encode(to encoder: any Encoder) throws {
>          var container = encoder.container(keyedBy: CodingKeys.self)
>          switch self {
>          case .bool(_: _):
> +            let _ = container.superEncoder(forKey: CodingKeys.bool)
> -            break
> ```
> and it is unclear to me whether this is expected behavior from @IgnoreCodingInitialized or if the tests were just wrong.

> I believe the previous behavior of @IgnoreCodingInitialized was a bug as I think on enums it is only meant to ignore the associated values, not the whole value. This PR fixes the bug but this might break implementations relying on that bug as they may have misinterpreted @IgnoreCodingInitialized to mean "ignore encoding completely". Thoughts are appreciated, if you say the fix is fine then I update the old tests.

The intent of `IgnoreCodingInitialized` functionality was to ignore decoding/encoding for initialized properties, i.e. associated variables with default values. So for this example `bool(_ variableBool: Bool = true)` will be encoded as if `bool`. The bug you have found is applicable for these as well which your fix will address.

You can go ahead and update the tests.

**Comment by Amzd** [comment]
done

**Comment by Amzd** [comment]
I modified only 9 lines of code and added 8 new tests, how tf did code coverage go down according to that bot..

**Review by soumyamahunt — APPROVED** [review]

**Comment by soumyamahunt** [comment]
> I modified only 9 lines of code and added 8 new tests, how tf did code coverage go down according to that bot..

It might be because of this change some of the lines that are covered earlier are no longer covered in tests. The decrease is very minimal and from what I see in the report is not that important to be covered.

I am merging this PR, feel free to create new PR if you want to make any other changes.

**Comment by abdul10ahad** [comment]
when would this get released?

**Comment by soumyamahunt** [comment]
> when would this get released?

@abdul10ahad I will not be available for rest of Feb and most of March. Probably late March or early April I will be releasing this.

**Comment by JarnoRFB** [comment]
@soumyamahunt would be great to understand if this can get released. It will definitely help to simplify some parts of our code 🙏

**Comment by soumyamahunt** [comment]
@JarnoRFB sorry for the delay and thank you for the reminder. I have released this fix in the latest release: [v1.6.1](https://github.com/SwiftyLab/MetaCodable/releases/tag/v1.6.1)
