### PR TITLE
fix: @Codable fails in structs with static members.

### LINKED ISSUE #26: [Bug] @Codable fails in structs with static members.
In my testing `@Codable` fails for structs which include static members:

``` swift
@Codable
struct Test {
  static var test = "test"
}
```
Fails with `Failed to receive result from plugin (from macro 'Codable')`.

It also fails in all other common permutations (with normal members etc.)

A working workaround for now is to declare these static members in an extension.

### PR DESCRIPTION
**Pull request by Midbin**
This fixes #26. 

Please note that I ran into, what I think, is a small swift compiler bug.
My workaround is in `RegistrationAttribut.swift:45-52` and `StaticVariableDeclaration.swift:46-50`.

This is based on #34 because it also adds new tests and I will rebase this PR when #34 lands.

### CODE REVIEW

File: Sources/CodableMacroPlugin/Attributes/RegistrationAttribute.swift [hunk 1]
```diff
@@ -42,6 +42,14 @@ extension RegistrationAttribute {
             guard let decl = member.decl.as(VariableDeclSyntax.self)
             else { return }
 
+            // The Macro fails to compile if the decl.modifiers.contains
+            // is directly used in the guard statement. Otherwise it should
+            // be used as a second condition in guard block above.
+            let isStaticVar = decl.modifiers.contains{$0.name.tokenKind == .keyword(.static)}
```
Comment (soumyamahunt) [inline Sources/CodableMacroPlugin/Attributes/RegistrationAttribute.swift:48]:
```suggestion
            let isStatic = decl.modifiers.contains { $0.name.tokenKind == .keyword(.static) }
```

File: Sources/CodableMacroPlugin/Attributes/RegistrationAttribute.swift [hunk 2]
```diff
@@ -42,6 +42,14 @@ extension RegistrationAttribute {
...
+            guard !isStaticVar else {
```
Comment (soumyamahunt) [inline Sources/CodableMacroPlugin/Attributes/RegistrationAttribute.swift:49]:
```suggestion
            guard !isStatic else { return }
```

File: Sources/CodableMacroPlugin/Attributes/KeyPath/CodedAt.swift [hunk 3]
```diff
@@ -37,13 +37,16 @@ struct CodedAt: PropertyAttribute {
...
+    /// * Attached declaration is not a static variable
+    ///   declaration
     /// * This attribute isn't used combined with `CodedIn`
     ///   and `IgnoreCoding` attribute.
     ///
     /// - Returns: The built diagnoser instance.
     func diagnoser() -> DiagnosticProducer {
         return AggregatedDiagnosticProducer {
             attachedToUngroupedVariable()
+            attachedToNonStaticVariable()
```
Comment (soumyamahunt) [inline Sources/CodableMacroPlugin/Attributes/KeyPath/CodedAt.swift:49]: Please add this to `Default` and `CodedBy` attributes as well.

**Review by soumyamahunt — CHANGES_REQUESTED** [review]

File: Sources/CodableMacroPlugin/Attributes/RegistrationAttribute.swift [hunk 4]
```diff
@@ -42,6 +42,14 @@ extension RegistrationAttribute {
             guard let decl = member.decl.as(VariableDeclSyntax.self)
             else { return }
 
+            // The Macro fails to compile if the decl.modifiers.contains
+            // is directly used in the guard statement. Otherwise it should
+            // be used as a second condition in guard block above.
+            let isStatic = decl.modifiers.contains { $0.name.tokenKind == .keyword(.static) }
+            guard !isStatic else { return }
+              return
+            }
```
Comment (soumyamahunt) [inline Sources/CodableMacroPlugin/Attributes/RegistrationAttribute.swift:51]:
```suggestion

```

File: Sources/CodableMacroPlugin/Attributes/RegistrationAttribute.swift [hunk 5]
```diff
@@ -42,6 +42,14 @@ extension RegistrationAttribute {
             guard let decl = member.decl.as(VariableDeclSyntax.self)
             else { return }
 
+            // The Macro fails to compile if the decl.modifiers.contains
+            // is directly used in the guard statement. Otherwise it should
+            // be used as a second condition in guard block above.
+            let isStatic = decl.modifiers.contains { $0.name.tokenKind == .keyword(.static) }
+            guard !isStatic else { return }
+              return
```
Comment (soumyamahunt) [inline Sources/CodableMacroPlugin/Attributes/RegistrationAttribute.swift:50]:
```suggestion
```

**Review by soumyamahunt — CHANGES_REQUESTED** [review]

File: Sources/CodableMacroPlugin/Diagnostics/StaticVariableDeclaration.swift [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+  @discardableResult
+  func produce(
+    for syntax: some SyntaxProtocol,
+    in context: some MacroExpansionContext
+  ) -> Bool {
+    // The Macro fails to compile if the .modifiers.contains
+    // is directly used in the guard statement.
+    let isStatic = syntax.as(VariableDeclSyntax.self)?
+      .modifiers.contains { $0.name.tokenKind == .keyword(.static) }
+    guard isStatic ?? false
```
Comment (soumyamahunt) [inline Sources/CodableMacroPlugin/Diagnostics/StaticVariableDeclaration.swift:50]:
```suggestion
    guard isStatic ?? false else { return false }
```

File: Sources/CodableMacroPlugin/Diagnostics/StaticVariableDeclaration.swift [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+    else { return false }
```
Comment (soumyamahunt) [inline Sources/CodableMacroPlugin/Diagnostics/StaticVariableDeclaration.swift:51]:
```suggestion
```

**Comment by soumyamahunt** [comment]
@Midbin please run swift-format as well:
```sh
swift run swift-format --in-place --ignore-unparsable-files --recursive Sources Tests
```

**Review by soumyamahunt — APPROVED** [review]
